import { useCallback, useEffect, FormEvent } from 'react'
import Head from 'next/head'

import { FiCheckCircle, FiArrowDownCircle, FiArrowUpLeft } from 'react-icons/fi'
import { AiOutlineWarning } from 'react-icons/ai'
import { MdAttachMoney } from 'react-icons/md'

import Header from '../Header'
import Footer from '../Footer'
import SearchForm from '../SearchForm'

import Presentation from '../Presentation'
import Error from '../Error'
import Loading from '../Loading'

import { useProduct } from '../../hooks/product/ProductProvider'
import { useMarketValue } from '../../hooks/market-value/MarketValueProvider'

import Product from '../../components/Product'

import baseStyle from '../../styles/base.module.css'

export default function MarketValue() {
  const { 
    product, 
    loadingProduct, 
    makeProduct,
    errorMessage
  }:any = useProduct()

  const { 
    similarProducts, 
    loadingSimilarProducts, 
    makeSimilarProducts
  }:any = useMarketValue()

  const handleSubmit = useCallback((e:FormEvent, value: string) => {
    e.preventDefault()
    makeProduct(value)
  }, [product])

  useEffect(() => {
    const init = () => {
      makeSimilarProducts(product)
    }

    if (product.id) init()
  }, [product])

  return (
    <div className={baseStyle.container}>
      <Head>
        <title>Valor de mercado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <main className={baseStyle.main}>
        <Header activeIdItem={2} />
        <SearchForm buttonText={'Adicionar'} placeholderText={"Insira a url do produto"} onSubmit={handleSubmit} />
        
        <section className={`${baseStyle.presentation} py-8`}>
          {(product && product.id && !loadingProduct) ? (
          <div className={baseStyle.content}>
            <hgroup className="mb-6">
              <h1 className="text-3xl mb-2">Valor de mercado</h1>
            </hgroup>

            <Product product={product}>
              <>
                {!similarProducts.length ? (
                    <div className={'flex items-center'}>
                      <div className={'mr-4'}>
                        <FiCheckCircle size={40} className={'text-green-500'} />
                      </div>
                      <div>
                        <span className={'font-bold text-green-500 text-2xl'}>Aprovado!</span>                       
                        <p className={'text-sm text-gray-500'}>Esse produto está com o melhor preço</p>
                      </div>
                    </div>
                  ) : (
                    <div className={'flex items-center'}>
                      <div className={'mr-4'}>
                        <AiOutlineWarning size={40} className={'text-yellow-500'} />
                      </div>
                      <div>
                        <span className={'font-bold text-yellow-500 text-2xl'}>Atenção!</span>                       
                        <p className={'text-sm text-gray-500'}>Existe {similarProducts.length} produto(s) com o melhor preço</p>
                      </div>
                    </div>
                )}
              </>
            </Product>

            {similarProducts.length && !loadingSimilarProducts ? (
              <>
                <hgroup className="mb-6">
                  <h2 className="text-sm text-gray-600">({similarProducts.length}) produto(s) encontrado(s)</h2>
                </hgroup>

                <div className="shadow border rounded-lg bg-white mb-6 divide-y divide-gray-200 divide-y height-full overflow-hidden">
                  {similarProducts.map((item: any, key: number) => (
                    <div key={`product-search-${key}`} className={`${baseStyle.currentProduct} px-4 py-4 divide-b flex items-center`}>
                      <div className={`${baseStyle.infoProduct} pr-4 w-3/5 flex items-center`}>
                        <div className={`${baseStyle.imageProduct} mr-4`}>
                          <a href={item?.permalink} target="_blank">
                            <img width="90" height="90" src={item?.thumbnail} className="ui-search-result-image__element" alt="Console Playstation 4 1tb Bundle 18 - Ps4" />
                          </a>
                        </div>
                        <div>
                          <span className={`${baseStyle.statusProduct} text-sm text-gray-400`}>
                            {item?.condition}
                          </span>
                          <h3 className={baseStyle.titleProduct}>
                            <a href={item?.permalink} target="_blank" className="block">
                              {item?.title}
                            </a>
                          </h3>
                          <div className={baseStyle.statusPrices}>
                            <span className={`${baseStyle.totalPrice} font-bold text-blue-500`}>
                              {item?.formatted_price}
                            </span>
                          </div>
                        </div>
                      </div>
                      <div className={`${baseStyle.resultsProduct} w-2/5`}>
                        <div className={`${baseStyle.resultsOk} flex items-center`}>
                          <div className={`${baseStyle.icon} mr-4`}>
                            <FiArrowDownCircle size={40} className={'text-green-500'} />
                          </div>
                          <div>
                            <span className={'font-bold text-green-500 text-2xl'}>{item.discount}%</span>                       
                            <p className={'text-sm text-gray-500'}>Esse produto está com um preço melhor</p>
                          </div>
                        </div>
                      </div>
                    </div> 
                  ))}
                </div> 
              </>
            ) : (
              <>
                {loadingSimilarProducts ? (
                  <Loading />
                ) : (
                  <div></div>
                )}
              </>
            )}
          </div>
          ) : (
            <>
              {loadingProduct ? (
                <div className={baseStyle.content}>
                  <Loading />
                </div>
              ) : (
                <div className={baseStyle.content}>
                  {!errorMessage ? (
                  <Presentation>
                    <span className="mb-2 border border-gray-200 rounded-full text-center p-4">
                      <MdAttachMoney size="74" className="text-blue-500" />
                    </span>
                    <h1 className="text-2xl mb-2">
                      Veja se o produto está dentro do valor de mercado
                    </h1>
                    <p className="text-gray-400 flex items-center">
                      <span className="mr-1">
                        <FiArrowUpLeft size="24" /> 
                      </span>
                      Adicione o link do produto no campo acima!
                    </p>
                  </Presentation>
                  ) : (
                    <Error messageText={errorMessage} />
                  )}
                </div>
              )}
            </>
          )}
        </section>
        <Footer />
      </main>
    </div>
  )
}
