import Head from 'next/head'
import baseStyle from '../styles/base.module.css'

import Header from '../components/Header'
import Footer from '../components/Footer'

import Presentation from '../components/Presentation'

import { FiArrowUpLeft } from "react-icons/fi";
import { BiErrorCircle } from "react-icons/bi";

export default function Comparator() {
  return (
    <div className={baseStyle.container}>
      <Head>
        <title>Pagina não encontrada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <main className={baseStyle.main}>
        <Header activeIdItem={0} />
        
        <section className={baseStyle.presentation + ' py-8'}>
        <div className={baseStyle.content}>
          <Presentation>
            <span className="mb-2 border border-gray-200 rounded-full text-center p-4">
              <BiErrorCircle size="74" className="text-blue-500" />
            </span>
            <h1 className="text-2xl mb-2">
              Pagina não encontrada
            </h1>
          </Presentation>
        </div>
        </section>

        <Footer />
      </main>
    </div>
  )
}
