import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { IoIosGitCompare } from "react-icons/io";
import { BsQuestion } from "react-icons/bs";
import { FiPlayCircle } from "react-icons/fi";
import { GiHealthNormal } from "react-icons/gi";

import {
  MdAttachMoney,
  MdStayPrimaryPortrait,
  MdLaptopMac,
  MdKitchen,
  MdHeadsetMic,
  MdDirectionsCar,
} from "react-icons/md";

import baseStyle from "../styles/base.module.css";

export default function Comparator() {
  return (
    <div className={baseStyle.container}>
      <Head>
        <title>Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <main className={baseStyle.main}>
        <section
          className={`${baseStyle.jumbotron} ${baseStyle.background} py-6 bg-yellow-400`}
        >
          <MdStayPrimaryPortrait
            size="48"
            className={`${baseStyle.svgIcon} text-gray-400`}
          />
          <MdLaptopMac
            size="48"
            className={`${baseStyle.svgIcon} text-gray-400`}
          />
          <MdKitchen size="48" className={`${baseStyle.svgIcon} text-gray-400`} />
          <MdHeadsetMic
            size="48"
            className={`${baseStyle.svgIcon} text-gray-400`}
          />
          <MdDirectionsCar
            size="48"
            className={`${baseStyle.svgIcon} text-gray-400`}
          />

          <div
            className={`${baseStyle.content} flex items-center justify-center px-2`}
          >
            <div>
              <hgroup className="mb-2">
                <h1
                  className={`${baseStyle.textShadow} text-white text-center lg:text-left mb-4 text-white text-shadow`}
                >
                  <span className="inline-flex mb-2 text-white items-center justify-center px-1 py-1 leading-none bg-white rounded-full">
                    <Image
                      src="/images/logo.jpg"
                      alt="Mercado livre"
                      width={39}
                      height={28}
                    />
                  </span>
                  <span className={'font-bold text-4xl lg:text-6xl mb-2 text-gray-900 block'}>Playground</span>
                </h1>
                <h2
                  className={`${baseStyle.textShadow} mb-2 opacity-50 text-center lg:text-left`}
                >
                  Experimente uma nova experiência de compra
                </h2>
              </hgroup>

              <ul className="flex flex-wrap justify-center mb-4 relative">
                <li className="p-2">
                  <div className="">
                    <Link href="/comparator">
                      <a
                        href=""
                        className="border hover:text-blue-500 flex flex-col items-center justify-center hover:border-blue-500 bg-white rounded w-28 h-28 shadow"
                      >
                        <IoIosGitCompare size="48" className="text-blue-500" />
                        <p className={`text-xs mt-1 px-2 block`}>Comparador</p>
                      </a>
                    </Link>
                  </div>
                </li>
                <li className="p-2">
                  <div className="">
                    <Link href="/market-value">
                      <a
                        href=""
                        className="border hover:text-blue-500 flex flex-col items-center justify-center hover:border-blue-500 bg-white rounded w-28 h-28 shadow"
                      >
                        <MdAttachMoney size="48" className="text-blue-500" />
                        <p className={`text-xs mt-1 px-2 block`}>
                          Valor de
                          <br />
                          mercado
                        </p>
                      </a>
                    </Link>
                  </div>
                </li>
                <li className="p-2">
                  <div className="">
                    <Link href="/ad-health">
                      <a
                        href=""
                        className="border hover:text-blue-500 flex flex-col items-center justify-center hover:border-blue-500 bg-white rounded w-28 h-28 shadow"
                      >
                        <GiHealthNormal size="40" className="text-blue-500" />
                        <p className={`text-xs mt-2 px-2 block text-center`}>
                          Saúde do
                          <br />
                          anúncio
                        </p>
                      </a>
                    </Link>
                  </div>
                </li>
                <li className="p-2">
                  <div className="">
                    <Link href="/what-is-the-price">
                      <a
                        href=""
                        className="border hover:text-blue-500 flex flex-col items-center justify-center hover:border-blue-500 bg-white rounded w-28 h-28 shadow"
                      >
                        <BsQuestion size="48" className="text-blue-500" />
                        <p className={`text-xs mt-1 px-2 block`}>
                          Qual é o preço?
                        </p>
                      </a>
                    </Link>
                  </div>
                </li>
                <li className="p-2">
                  <div className="">
                    <Link href="/videos">
                      <a
                        href=""
                        className="border hover:text-blue-500 flex flex-col items-center justify-center hover:border-blue-500 bg-white rounded w-28 h-28 shadow"
                      >
                        <FiPlayCircle size="48" className="text-blue-500" />
                        <p className={`text-xs mt-1 px-2 block`}>Videos</p>
                      </a>
                    </Link>
                  </div>
                </li>
              </ul>

              <p className="text-center text-xs opacity-25">
                Copyright © 1999-2021 Grupo Mercado Livre.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
